name: CI/CD CHIP-8

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y cmake clang-tidy

            - name: Build CHIP-8
              run: |
                mkdir build
                cd build
                cmake ..
                cmake --build .

            - name: Run Tests
              run: |
                cb build
                ctest --output-on-failure

            - name: Run Lint
              run: |
                cd build
                clang-tidy ../src/*.cpp -- -std=c++17
