name: CI/CD CHIP-8

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y cmake clang-tidy catch2

            - name: Build CHIP-8
              run: |
                mkdir build
                cd build
                cmake ..
                cmake --build .

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: chip8-build
                path: build/

    tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Download build artifacts
            uses: actions/download-artifact@v4
            with:
              name: chip8-build
              path: build/

          - name: Run Tests
            run: |
              cd build
              ./tests

    lint:
      runs-on: ubuntu-latest
      needs: build
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install clang-tidy
            run: sudo apt-get update && sudo apt-get install -y clang-tidy

          - name: Run Lint
            run: clang-tidy src/*.cpp -- -std=c++17
